HINT to use \copy when COPY rejected due to relative path
We already have a HINT on COPY as non-superuser saying:

ERROR:  must be superuser to COPY to or from a file
HINT:  Anyone can COPY to stdout or from stdin. psql's \copy command
also works for anyone.

but superusers will get:

ERROR: relative path not allowed for COPY to file

if they get confused between COPY and \copy .

This adds a HINT:

HINT: COPY uses server-side paths. You might be looking for the 'psql'
client's \copy command